user:
  fullname:
    max_length: 50
user_project:
  title_max_length: 50
  description_max_length: 1000
user_profiles:
  bio_max_length: 10000
  current_address_max_length: 255
  education_max_length: 1000
company:
  name_max_length: 50
  description_max_length: 1000
  page_size: 6
  truncate_description: 100
image:
  max_size: 5
  acceptable_types: ["image/jpg", "image/jpeg", "image/png", "image/gif"]    
jobs:
  page_size: 4
  description_max_length: 1000
  title_max_length: 100
  filter_locations: ["Hà Nội", "Đà Nẵng", "Hồ Chí Minh"]
  related_jobs_size: 5
  max_salary: 1000000
  salary_filter_step: 100
interview:
  datetime_format: "%B %d, %Y %H:%M"
enterprise_scout:
  page_size: 12
roles:
  user: 0
  enterprise: 1
  admin: 2
apply:
  page_size: 9
interview_process:
  interviewer_name_max_length: 255
  interview_location_max_length: 255
  feedback_max_length: 1000
  rating_min_value: 1
  rating_max_value: 5
jwt_default_exp_hours: 12
